### PR TITLE
Added Andrew Cherry

### PR DESCRIPTION
**Pull request by kolektiv**

### CODE REVIEW

**Comment by mathias-brandewinder** [comment]
Hi @kolektiv ! Would you mind updating your PR, and pick your 5 'favorite' tags out of the ones you proposed? Thanks in advance :)

**Comment by kolektiv** [comment]
Done! Although I'm not sure where a conflict has emerged from. Let me know if you need me to tweak anything else :)

**Comment by ReedCopsey** [comment]
Not sure why there's conflicts - just copied the edits in manually.

Thanks @kolektiv !

**Comment by kolektiv** [comment]
Thanks!

**Pull request closed without merging**
